#! /bin/bash

DIR=$1

# Check first argument is valid
if [ -z "$1" ]; then
    echo "Usage: $0 <new_directory_name>"
    exit 1
fi

# Exit if directory exists
if [[ -d $DIR ]]; then
    echo directory $DIR already exists. doing nothing.
    exit 2
fi

mkdir $DIR
cd $DIR
# Create squeleton files
touch meson.build
cat <<EOT >> meson.build
# project name and type (cpp)
project('myproject', 'cpp', version : '0.1', default_options : ['warning_level=3', 'cpp_std=c++14'])
# name executable and entry file
executable('out', 'main.cpp', install : true)
EOT

touch main.cpp
cat <<EOT >> main.cpp
#include <iostream>

using namespace std;

int main(void) {
    int a, b;
    cin >> a >> b;

    cout << "ok";
    return 0;
}
EOT

# meson setup (one time setup)
BUILDDIR='builddir'
mkdir -p $BUILDDIR
meson $BUILDDIR
