#! /bin/bash

DIR=$1

# Check first argument is valid
if [ -z "$1" ]; then
    echo "Usage: $0 <new_directory_name>"
    exit 1
fi

BUILDDIR='builddir'
EXECUTABLE='out'

pushd $DIR

# mkdir -p $BUILDDIR
# meson $BUILDDIR

ninja -C ${BUILDDIR}
echo "Running './${BUILDDIR}/${EXECUTABLE}'"
echo ' '
./${BUILDDIR}/${EXECUTABLE}

